config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "movies#index"
  # Routes for the Movie resource:
  # CREATE
  get "/movies/new", :controller => "movies", :action => "new"
  post "/create_movie", :controller => "movies", :action => "create"

  # READ
  get "/movies", :controller => "movies", :action => "index"
  get "/movies/:id", :controller => "movies", :action => "show"

  # UPDATE
  get "/movies/:id/edit", :controller => "movies", :action => "edit"
  post "/update_movie/:id", :controller => "movies", :action => "update"

  # DELETE
  get "/delete_movie/:id", :controller => "movies", :action => "destroy"
  #------------------------------

  devise_for :directors
  # Routes for the Director resource:
  # READ
  get "/directors", :controller => "directors", :action => "index"
  get "/directors/:id", :controller => "directors", :action => "show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  # Direct associations

  has_many   :movies,
             :dependent => :destroy

  # Indirect associations

  # Validations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/movie.rb
class Movie < ApplicationRecord
  # Direct associations

  belongs_to :director

  # Indirect associations

  # Validations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_director!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, :keys => [:name])

    devise_parameter_sanitizer.permit(:account_update, :keys => [:name])
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new
    @movie.title = params[:title]
    @movie.director_id = params[:director_id]

    if @movie.save
      redirect_to "/movies", :notice => "Movie created successfully."
    else
      render 'new'
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    @movie.title = params[:title]
    @movie.director_id = params[:director_id]

    if @movie.save
      redirect_to "/movies", :notice => "Movie updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])

    @movie.destroy

    redirect_to "/movies", :notice => "Movie deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/index.html.erb
<div class="page-header">
  <h1>
    Directors
    <a href="/directors/new" class="btn btn-lg btn-success">New Director</a>
  </h1>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Actions</th>
      </tr>

      <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
        <td><%= director.email %></td>
        <td><%= director.password %></td>
        <td>
          <a href="/directors/<%= director.id %>" class="btn btn-primary">Show</a>
          <a href="/directors/<%= director.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/delete_director/<%= director.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/directors/show.html.erb
<div class="page-header">
  <h3>Director #<%= @director.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><%= @director.name %></dd>

      <dt>Email</dt>
      <dd><%= @director.email %></dd>

      <dt>Password</dt>
      <dd><%= @director.password %></dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/directors" class="btn btn-primary">
        Back
      </a>
      <a href="/directors/<%= @director.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_director/<%= @director.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sgaigfaasmhf2</title>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">Sgaigfaasmhf2</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/movies">Movies</a></li>
          <li><a href="/directors">Directors</a></li>
          <li><a href="/rails/info">Sitemap</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_director.present? %>
            <li>
              <a href="/directors/edit">
                <%= current_director.name %>
              </a>
            </li>

            <li>
              <a href="/directors/sign_out" data-method="delete" rel="nofollow">
                Sign Out
              </a>
            </li>
          <% else %>
            <li>
              <a href="/directors/sign_up">
                Sign Up
              </a>
            </li>

            <li>
              <a href="/directors/sign_in">
                Sign In
              </a>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/movies/edit.html.erb
<!-- Validation failure messages -->
<% if @movie.errors.any? %>
  <% @movie.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Edit Movie #<%= @movie.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_movie/<%= @movie.id %>" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for title -->
      <div class="form-group">
        <label for="title" class="control-label">
          Title
        </label>

        <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @movie.title %>">
      </div>

      <!-- Label and input for director_id -->
      <div class="form-group">
        <label for="director_id" class="control-label">
          Director
        </label>

        <%= select_tag(:director_id, options_from_collection_for_select(Director.all, :id, :name, @movie.director_id), :class => "form-control") %>
      </div>

      <button class="btn btn-warning">
        Update Movie
      </button>
      or
      <a href="/movies/<%= @movie.id %>">Cancel</a>
    </form>
  </div>
</div>

app/views/movies/index.html.erb
<div class="page-header">
  <h1>
    Movies
    <a href="/movies/new" class="btn btn-lg btn-success">New Movie</a>
  </h1>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Title</th>
        <th>Director</th>
        <th>Actions</th>
      </tr>

      <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.director.name %></td>
        <td>
          <a href="/movies/<%= movie.id %>" class="btn btn-primary">Show</a>
          <a href="/movies/<%= movie.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/delete_movie/<%= movie.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/movies/new.html.erb
<!-- Validation failure messages -->
<% if @movie.errors.any? %>
  <% @movie.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<div class="page-header">
  <h3>Add Movie</h3>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/create_movie" method="post">
      <!-- Hidden input for authenticity token to protect from forgery -->
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

      <!-- Label and input for title -->
      <div class="form-group">
        <label for="title" class="control-label">
          Title
        </label>

        <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @movie.title %>">
      </div>

      <!-- Label and input for director_id -->
      <div class="form-group">
        <label for="director_id" class="control-label">
          Director
        </label>

        <%= select_tag(:director_id, options_from_collection_for_select(Director.all, :id, :name, @movie.director_id), :class => "form-control") %>
      </div>

      <button class="btn btn-success">
        Create Movie
      </button>
      or
      <a href="/movies">Cancel</a>
    </form>
  </div>
</div>

app/views/movies/show.html.erb
<div class="page-header">
  <h3>Movie #<%= @movie.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt>Title</dt>
      <dd><%= @movie.title %></dd>

      <dt>Director</dt>
      <dd><%= @movie.director_id %></dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/movies" class="btn btn-primary">
        Back
      </a>
      <a href="/movies/<%= @movie.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_movie/<%= @movie.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>